name: medibot
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.4.3
  shared_preferences: ^2.2.3
  device_info_plus: ^11.2.1
  image_picker: ^1.1.1
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.3.1
  logger: ^2.3.0
  fluttertoast: ^8.2.6
  permission_handler: ^11.3.1
  webview_flutter: ^4.8.0
  intl: ^0.20.1
  internet_connection_checker: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic



