name: pingmexx
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2

  shared_preferences: ^2.5.3
  device_info_plus: ^11.4.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  fluttertoast: ^8.2.12
  permission_handler: ^12.0.0+1
  webview_flutter: ^4.13.0
  intl: ^0.20.2
  internet_connection_checker: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html: ^0.16.0
  flutter_dotenv: ^5.0.2

  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  firebase_analytics: ^11.4.6
  google_sign_in: ^6.3.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  no_screenshot: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
dependency_overrides:
  dio: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - .env


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic



